name: Publish UPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upm-release-any-processor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: main
        upm_tag_prefix: any-processor/v
        upm_package_path: Packages/com.quabug.any-processor
        create_unitypackage: true
        unitypackage_name: AnyProcessor
        
  upm-release-any-serialize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: main
        upm_tag_prefix: any-serialize/v
        upm_package_path: Packages/com.quabug.any-serialize
        create_unitypackage: true
        unitypackage_name: AnySerialize
        
