name: unity-test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - Mono2x
          - IL2CPP
        unityVersion:
          - 2020.3.38f1
          - 2021.3.8f1
          - 2022.1.13f1
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - uses: game-ci/unity-test-runner@v2
        id: unity-test
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          customImage: unityci/editor:${{ matrix.unityVersion }}-base-1
          customParameters: -scriptingBackend ${{ matrix.backend }} -testCategory "!benchmark"
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.unityVersion }}(${{ matrix.backend }})
          path: ${{ steps.unity-test.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results for ${{ matrix.unityVersion }}(${{ matrix.backend }})
          path: ${{ steps.unity-test.outputs.coveragePath }}
